import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { buildRetentionPrintHtml } from "../client/src/lib/retention-document-print";
import type { RetentionSnapshot } from "../shared/retention-documents";

describe("original preprinted retention format", () => {
  // Fixtures generated by the original Facturas handler at 5260a3c^.
  for (const name of ["hnl", "usd", "eight-concepts"]) {
    it("preserves the original HTML byte for byte: " + name, () => {
      const base = new URL(
        "./fixtures/retention-preprinted/" + name,
        import.meta.url
      );
      const document = JSON.parse(
        readFileSync(new URL(base + ".json"), "utf8")
      ) as {
        currency: string;
        snapshot: RetentionSnapshot;
      };
      const expected = JSON.parse(
        readFileSync(new URL(base + ".expected.json"), "utf8")
      ).html as string;
      expect(
        buildRetentionPrintHtml({
          ...document,
          documentNumber: "001-001-01-00000001",
          status: "registrada",
          total: "1.0000",
        })
      ).toBe(expected);
    });
  }
});
